language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
after_success:
    - echo "Build succeeded!"
after_failure:
    - echo "Something went wrong..."
os:
    - linux
before_install:
    - sudo apt-get update --fix-missing && sudo apt-get install -y cmake libsndfile1-dev libpulse-dev libasound2-dev libsdl-dev liblo-dev libsdl2-dev
    - sudo cp bin/* /usr/bin/
script:
    - cargo test --all -- --nocapture