language: cpp
after_success:
    - echo "Build succeeded!"
after_failure:
    - echo "Something went wrong..."
before_install:
    - eval "${MATRIX_EVAL}"
script:
    - cd scripts && ./getdeps.sh && ./builddeps.sh && cd ..
    - cd build && cmake -G Ninja .. && ninja
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      compiler:
        - clang
        - gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - cmake
            - ninja-build
            - libsndfile1-dev
            - libpulse-dev
            - libasound2-dev
            - liblo-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    
