name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make build dir
      run: mkdir -p build
    - name: use build dir
      run: cd build
    - name: run cmake
      run: cmake -GNinja ..
    - name: run ninja
      run: ninja
